/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type WishlistItem,
    WishlistItemFromJSON,
    WishlistItemToJSON,
} from '../models/WishlistItem';

export interface CreateWishlistItemRequest {
    /**
     * 
     */
    wishlistItem: WishlistItem;
}

export interface DeleteWishlistItemRequest {
    /**
     * 
     */
    id: number;
}

export interface GetWishlistItemRequest {
    /**
     * 
     */
    id: number;
}

export interface UpdateWishlistItemRequest {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    wishlistItem: WishlistItem;
}

/**
 * 
 */
export class WishlistApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWishlistItem without sending the request
     */
    async createWishlistItemRequestOpts(requestParameters: CreateWishlistItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wishlistItem'] == null) {
            throw new runtime.RequiredError(
                'wishlistItem',
                'Required parameter "wishlistItem" was null or undefined when calling createWishlistItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wishlist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WishlistItemToJSON(requestParameters['wishlistItem']),
        };
    }

    /**
     * Save a pet
     */
    async createWishlistItemRaw(requestParameters: CreateWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishlistItem>> {
        const requestOptions = await this.createWishlistItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishlistItemFromJSON(jsonValue));
    }

    /**
     * Save a pet
     */
    async createWishlistItem(requestParameters: CreateWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishlistItem> {
        const response = await this.createWishlistItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWishlistItem without sending the request
     */
    async deleteWishlistItemRequestOpts(requestParameters: DeleteWishlistItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWishlistItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/wishlist/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a saved pet
     */
    async deleteWishlistItemRaw(requestParameters: DeleteWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWishlistItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a saved pet
     */
    async deleteWishlistItem(requestParameters: DeleteWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWishlistItemRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getWishlistItem without sending the request
     */
    async getWishlistItemRequestOpts(requestParameters: GetWishlistItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWishlistItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/wishlist/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a saved pet
     */
    async getWishlistItemRaw(requestParameters: GetWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishlistItem>> {
        const requestOptions = await this.getWishlistItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishlistItemFromJSON(jsonValue));
    }

    /**
     * Get a saved pet
     */
    async getWishlistItem(requestParameters: GetWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishlistItem> {
        const response = await this.getWishlistItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWishlistItems without sending the request
     */
    async listWishlistItemsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/wishlist`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List saved pets
     */
    async listWishlistItemsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WishlistItem>>> {
        const requestOptions = await this.listWishlistItemsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WishlistItemFromJSON));
    }

    /**
     * List saved pets
     */
    async listWishlistItems(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WishlistItem>> {
        const response = await this.listWishlistItemsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWishlistItem without sending the request
     */
    async updateWishlistItemRequestOpts(requestParameters: UpdateWishlistItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWishlistItem().'
            );
        }

        if (requestParameters['wishlistItem'] == null) {
            throw new runtime.RequiredError(
                'wishlistItem',
                'Required parameter "wishlistItem" was null or undefined when calling updateWishlistItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/wishlist/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WishlistItemToJSON(requestParameters['wishlistItem']),
        };
    }

    /**
     * Update a saved pet
     */
    async updateWishlistItemRaw(requestParameters: UpdateWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishlistItem>> {
        const requestOptions = await this.updateWishlistItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishlistItemFromJSON(jsonValue));
    }

    /**
     * Update a saved pet
     */
    async updateWishlistItem(requestParameters: UpdateWishlistItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishlistItem> {
        const response = await this.updateWishlistItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
