/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PetNote
 */
export interface PetNote {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    petId: number;
    /**
     * 
     */
    text: string;
}

/**
 * Check if a given object implements the PetNote interface.
 */
export function instanceOfPetNote(value: object): value is PetNote {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PetNoteFromJSON(json: any): PetNote {
    return PetNoteFromJSONTyped(json, false);
}

export function PetNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetNote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'petId': json['petId'],
        'text': json['text'],
    };
}

export function PetNoteToJSON(json: any): PetNote {
    return PetNoteToJSONTyped(json, false);
}

export function PetNoteToJSONTyped(value?: PetNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'petId': value['petId'],
        'text': value['text'],
    };
}

