/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WishlistItem
 */
export interface WishlistItem {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    petId: number;
}

/**
 * Check if a given object implements the WishlistItem interface.
 */
export function instanceOfWishlistItem(value: object): value is WishlistItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('petId' in value) || value['petId'] === undefined) return false;
    return true;
}

export function WishlistItemFromJSON(json: any): WishlistItem {
    return WishlistItemFromJSONTyped(json, false);
}

export function WishlistItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishlistItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'petId': json['petId'],
    };
}

export function WishlistItemToJSON(json: any): WishlistItem {
    return WishlistItemToJSONTyped(json, false);
}

export function WishlistItemToJSONTyped(value?: WishlistItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'petId': value['petId'],
    };
}

